title: KGWRAPS
logo: assets/logos/logo.png
description: Task Adaptation with Shared Knowledge for Multi-Agent Teaming Systems
show_downloads: false

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
