title: KGWRAPS
logo: assets/logos/logo.png
description: A Knowledge Graph-poWered Research Assistant for Polymer Science
show_downloads: false

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
